casepro/msgs/migrations/0027_message_has_labels.py
casepro/msgs/migrations/0028_message_triggers.py
casepro/msgs/migrations/0029_folder_indexes_pt3.py
casepro/msgs/models.py
casepro/msgs/tests.py
casepro/sql/__init__.py
casepro/sql/msgs_0001.sql

Admins see messages with all labels for their org but filtering over all labels to determine if a message belongs in the Inbox (i.e. it's labelled) or the Unlabelled folder, is slow. This adds a `has_labels` field which is maintained by a db trigger.

Add has_labels flag to Message to speed up admin views

---

casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/cases/tests.py
casepro/contacts/migrations/0019_group_is_dynamic.py
casepro/contacts/models.py
casepro/contacts/tests.py
casepro/orgs_ext/forms.py
casepro/orgs_ext/views.py
casepro/test.py
pip-freeze.txt

* adds `is_dynamic` field to `Group`
* prevents trying to suspend contacts from or restore contacts to dynamic groups
* don't list dynamic groups as options for group suspension
Once this has been deployed and groups are re-synced on prod - then can push another change to unmark any dynamic groups as suspend groups.

Dynamic group support

---

casepro/backend/__init__.py
casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/cases/models.py
casepro/cases/tests.py
casepro/cases/views.py
casepro/msgs/migrations/0034_auto_20160512_1200.py
casepro/msgs/migrations/0035_populate_outgoing_contacts.py
casepro/msgs/models.py
casepro/msgs/tests.py
casepro/msgs/views.py
casepro/settings_common.py
static/coffee/controllers.coffee
static/coffee/modals.coffee
static/coffee/services.coffee

- Splits the generic message sending endpoint into three more logical endpoints for case replies, bulk replies and forwards
- Records contacts and URNs on the outgoing message
- Fixes a bug on the forwarding modal dialog

Outgoing message improvements

---

casepro/cases/migrations/0036_caseexport_partner.py
casepro/msgs/migrations/0046_exports_partner.py
casepro/msgs/tests.py
casepro/utils/export.py

Added partner field to exports and only let partner users download exports that their partner org has created. Org admins can access all exports for their org.

Lock down export access for partner users

---

casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/cases/context_processors.py
casepro/cases/tests.py
casepro/contacts/models.py
casepro/contacts/tests.py
casepro/contacts/views.py
casepro/msgs/models.py
casepro/msgs/tests.py
casepro/settings_common.py
static/coffee/services.coffee
templates/cases/case_read.haml
templates/cases/home_messages.haml
templates/cases/home_outgoing.haml
templates/cases/partner_read.haml
templates/contacts/contact_read.haml

- Switches frontend code to reference contacts by local id rather than backend UUID (which they might not have in some deployments)
- Allows deployments to switch between displaying contact names and anonymous identifiers using setting
- Adds very basic contact read page:

Basic contact page and contact displayer/identifier changes

---

casepro/cases/forms.py
casepro/cases/migrations/0036_partner_is_restricted.py
casepro/cases/models.py
casepro/cases/tests.py
casepro/cases/views.py
casepro/msgs/models.py
casepro/orgs_ext/tests.py
casepro/test.py
templates/cases/partner_create.haml
templates/cases/partner_list.haml
templates/cases/partner_read.haml
templates/cases/partner_update.haml

Some UPartners offices have created partner orgs which they use internally and explicitly have access to all labels. This isn't ideal from a display or performance point-of-view especially when number of labels is high.
This should also serve Momconnect usecase where partners aren't restricted by labels.
Also changes partner form to use choeckboxes rather than dropdown as this makes it easier to see which labels are selected.

Allow some partners to have unrestricted label access

---

casepro/cases/tests.py
casepro/cases/views.py
casepro/msgs/tests.py
casepro/msgs/views.py
casepro/settings_common.py
casepro/test.py
casepro/utils/middleware.py
casepro/utils/tests.py
karma/test-services.coffee
pip-freeze.txt
static/coffee/services.coffee

* Switches all service methods that post to endpoints to use JSON rather than `FormData`. This is the Angular default way and makes it simpler to test.
* Improves service method unit tests to check POST body

Use JSON for AJAX posts

---

karma/helpers.coffee
karma/test-controllers.coffee
karma/test-filters.coffee
karma/test-services.coffee
static/coffee/controllers.coffee
static/coffee/services.coffee
templates/cases/home_base.haml

* all modal creating service methods now return promises rather than taking callbacks
* server time now used for start point of item fetches
* removed new item fetching code for cases - current implementation relies on browser time and so isn't reliable. Need to figure out mechanism for new item fetching that will work for messages and cases.
* changed `BaseItemsController` to only load old items if active label actually changes - means item fetching is started by the `infinite-scroll` directive on the page rather than from controller initialisation
* consistent use of parentheses for coffeescript function calls
* more frontend test coverage

More frontend testing and cleanup

---

casepro/profiles/__init__.py
casepro/profiles/migrations/0004_fix_deleted_users.py
casepro/profiles/tests.py
casepro/profiles/views.py

So that it's easier to put them back in that org or other orgs. Includes migration to reactivate deleted users but remove them from all orgs.

Don't delete users, just remove them from orgs

---

casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/cases/tests.py
casepro/msgs/migrations/0047_outgoing_urn.py
casepro/msgs/models.py
casepro/msgs/tests.py
casepro/msgs/views.py

Outgoing instances in CasePro used to model broadcasts in RapidPro. This makes forwards more like replies in that they model a single message, and is a preparation step for actually surfacing forwards somewhere in the UI - like the Replies tab on the partner pages.

Change modelling of forwards so that there is one URN per Outgoing

---

casepro/cases/mixins.py
casepro/cases/tests.py
casepro/cases/views.py
casepro/orgs_ext/__init__.py
casepro/orgs_ext/mixins.py
casepro/profiles/__init__.py
casepro/profiles/forms.py
casepro/profiles/models.py
casepro/profiles/tests.py
casepro/profiles/urls.py
casepro/profiles/views.py
casepro/settings_common.py
casepro/test.py
templates/profiles/user_create.haml
templates/profiles/user_update.haml

Reworks user editing UIs so that there 3 views:
1. Creating any kind of user from the org administration (accessible to org admins and superusers)
2. Creating a partner user from the partner dashboard (accessible to partner managers and org admins)
3. Updating any kind of user (accessible to all of above, tho partner managers can't change a user's partner)
Screenshot of 1 when logged in org admin:
Options reduced when logged in partner manager

Allow admin users to create other admin users and add password complexity checks

---

casepro/cases/management/commands/perftest.py
pip-freeze.txt
pip-requires.txt

Runs through all orgs and all partners within those orgs, testing a set of views to find slow spots. `--verbosity=2` causes it to dump out details of each request. By default just prints a list problems, e.g.
(NB that first problem is for an endpoint which isn't yet used or optimised for usage outside of the context of a partner org)

Added management command for testing views as different users

---

casepro/msgs/forms.py
casepro/msgs/migrations/0048_label_rule.py
casepro/msgs/migrations/0049_remove_label_tests.py
casepro/msgs/models.py
casepro/msgs/tests.py
casepro/msgs/views.py
casepro/rules/migrations/0001_initial.py
casepro/rules/mixins.py
casepro/rules/models.py
casepro/rules/tests.py
casepro/rules/urls.py
casepro/rules/views.py
casepro/settings_common.py
casepro/test.py
casepro/urls.py
karma/test-controllers.coffee
static/coffee/controllers.coffee

- Adds option to ignore single word messages
- Fixes bug on home page where labelling dropdown isn't populated until active label is changed
- Adds support for non-ascii keywords
- Changes keyword min length to 2
- Adds basic rule list page (not linked from anywhere for now, really just for debugging)

Labelling improvements

---

casepro/cases/tests.py
casepro/cases/views.py
casepro/msgs/tests.py
casepro/msgs/views.py

Users can apply individual labels to messages and cases, or open a labelling modal that let's them select multiple labels. This doesn't show labels that the user doesn't have access to, and these labels were then being removed when the modal form was submitted.

Don't let users remove labels they don't have access to

---

casepro/cases/migrations/0039_populate_case_watchers.py
casepro/cases/models.py
karma/test-services.coffee
static/coffee/services.coffee

1. Adds migration to add users as watchers on existing cases
2. Case actions which automatically make the user a watcher now limited to:
* Opening
* Reopening
* Adding a note
* Replying

Case activity notification changes

---

casepro/profiles/migrations/0005_fix_admins_with_partners.py

At one point admin users could also be added to partner orgs. That's been fixed so that users can only be one thing per org, but still a handful of users in our db who are both.

Migration to fix admin users who are also partner users in the same org

---

templates/cases/inbox_messages.haml

Also replaces usages of `%span.glyphicon` with `%i.glyphicon` for consistency.

Replace contact link with button on inbox view

---

casepro/msgs/tests.py
casepro/orgs_ext/views.py
casepro/statistics/migrations/0003_auto_20160701_1412.py
casepro/statistics/migrations/0004_populate_incomining_counts.py
casepro/statistics/models.py
casepro/statistics/signals.py
casepro/statistics/tests.py
templates/orgs_ext/org_home.haml

Keeps track of number of incoming messages received each day using `DailyCount`. If labels on existing messages are manually changed after message is received, counts are updated accordingly.

Track incoming messages by org and label

---

casepro/cases/models.py
casepro/msgs/models.py
casepro/msgs/tests.py
casepro/msgs/views.py
casepro/settings_common.py
casepro/statistics/models.py
casepro/statistics/signals.py
casepro/statistics/tests.py
casepro/statistics/urls.py
casepro/statistics/views.py
casepro/utils/__init__.py
casepro/utils/tests.py
static/coffee/controllers.coffee
static/coffee/services.coffee
templates/cases/inbox_base.haml
templates/cases/partner_read.haml
templates/frame.haml
templates/msgs/label_read.haml
templates/orgs_ext/org_home.haml

Replaces label list page with new Labels tab on org dashboard:
Clicking on a label takes user to new label dashboard. For now just has simple summary but from here users can edit/delete the label - and after subsequent PR - this is where they will also watch/unwatch a label.

Simple label dashboard

---

karma/test-controllers.coffee
static/coffee/controllers.coffee
templates/cases/partner_read.haml
templates/msgs/label_read.haml
templates/orgs_ext/org_home.haml

For example, the URL `/org/home/#/labels` now goes directly to the labels tab on the org dashboard

Reflect tab changes in url so that specific tabs can be linked to

---

casepro/msgs/models.py

Inbox views are faster when they use the `msgs_inbox` partial index which checks for `has_labels=TRUE`, so we must include this in the queryset even when filtering by a specific label.

Ensure inbox db index is used during all label-specific searches

---

karma/test-filters.coffee
static/coffee/filters.coffee
templates/cases/inbox_base.haml

To allow wrapping of long label names, e.g.

Display label names with underscores as spaces in inbox

---

casepro/settings.py.dev

There is a small change that we can make to the dev/testing settings file to improve test run time, from 379.215s to 278.501s on my local machine.

Change password hasher to cheaper one for test run speedup

---

casepro/settings.py.dev
casepro/settings_common.py

@rudigiesler no sooner had I merged that last PR did I realise this changes it for my local dev instance even when not testing. Does change below work for you?

Set the password hasher to MD5 for tests only and not in settings.py.dev

---

casepro/backend/__init__.py
casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/cases/models.py
casepro/cases/tests.py
casepro/msgs/models.py
casepro/msgs/tests.py
casepro/utils/__init__.py
casepro/utils/tests.py
karma/test-services.coffee
static/coffee/services.coffee
templates/cases/case_read.haml

* `backend.fetch_contact_messages(...)` now returns transient model instances rather than translating backend JSON into CasePro JSON. This allows JSON rendering of case timelines to be handled in view layer like everything else.
* `TimelineItem` utility class simplifies JSON rendering of timeline items
We'll likely be adding a timeline of messages to the contact page and these changes will aid with that.

Simpler timeline rendering 

---

karma/test-controllers.coffee
static/coffee/controllers.coffee

https://github.com/rapidpro/casepro/pull/85 fixed tabs so that tab changes are reflected in the URL, and that when a page is reloaded, the initial tab is activated based on the URL.
But it doesn't update the active tab if the location changes but the page isn't reloaded (e.g. changing tabs, and then pressing the browser back button). This PR fixes that.

Tabbed pages fix

---

casepro/cases/views.py
casepro/contacts/models.py
karma/test-directives.coffee
static/coffee/controllers.coffee
static/coffee/directives.coffee
templates/cases/case_read.haml
templates/cases/inbox_messages.haml
templates/cases/inbox_outgoing.haml
templates/cases/partner_read.haml
templates/partials/directive_contact_details.haml
templates/partials/popover_contact.haml

Also updates the styling of the contact details panel on the case page, to use same styling as that which will be used for pods provided by case plugins.
And ensures that date and numerical field values are formatted accordingly. So
becomes:

Render contact fields using labels

---

casepro/contacts/models.py
casepro/contacts/tests.py
casepro/contacts/views.py
casepro/utils/__init__.py
casepro/utils/tests.py
pip-freeze.txt
pip-requires.txt
templates/cases/case_read.haml

Also adds language to the contact details box on the case read page:

Translate language ISO codes into names when displaying

---

casepro/contacts/models.py
casepro/contacts/tests.py
karma/test-controllers.coffee
static/coffee/controllers.coffee
templates/contacts/contact_read.haml

These were inadvertently removed from this page by https://github.com/rapidpro/casepro/pull/112
If contact doesn't belong to any groups:

Restore contact groups on contact read page

---

casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/contacts/migrations/0021_contact_is_stopped_pt1.py
casepro/contacts/migrations/0022_contact_is_stopped_pt2.py
casepro/contacts/models.py
casepro/contacts/tests.py
templates/cases/case_read.haml
templates/contacts/contact_read.haml

Adds `Contact.is_stopped` and displays both this and `Contact.is_blocked` on the contact and case read pages, if they are set. If they're not set, nothing is displayed so no confusion if these fields aren't being used.
On the contact read page:
and on the case page:

Display contact status (blocked and/or stopped)

---

casepro/profiles/tests.py
casepro/profiles/views.py

* Creating a new admin user should redirect to users tab on org dashbaord
* Creating a new partner user should redirect to users tab on partner dashboard
Fixes https://github.com/rapidpro/casepro/issues/120

Fix redirects when creating new users

---

casepro/cases/migrations/0040_partner_users.py
casepro/cases/migrations/0041_populate_partner_users.py
casepro/cases/models.py
casepro/profiles/__init__.py
casepro/profiles/migrations/0007_remove_profile_partner.py
casepro/profiles/models.py
casepro/profiles/tests.py
casepro/profiles/views.py

Replaces `Profile.partner` with `User.partners` / `Partner.users` many-to-many.
Users can still only be in one partner in a given org - but they can be in a partner in one org - and in another partner in another org.
Also moves `get_role` and `update_role` onto `User` class as `user.get_role(..)` makes more sense than `user.profile.get_role(..)` etc

Allow users to belong to different partners in different orgs

---

templates/cases/case_read.haml

A recent change caused pod directives to no longer get their controller's scope anymore since the directive is no longer a child of the element to which the controller is applied.

Fix pod rendering

---

casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/utils/email.py
static/coffee/modals.coffee
templates/partials/modal_compose.haml

UPartners want to be able to forward messages to phone numbers and email addresses, but RapidPro doesn't currently support email channels. 
This change allows the RapidPro backend to handle mailto: URNs by leveraging the internal CasePro email system.
Also switches email URN prefix to "mailto:"

RapidPro email forward sending using the CasePro email system

---

karma/test-directives.coffee
static/coffee/directives.coffee
templates/cases/inbox_outgoing.haml

Introduces a `cp-urn` directive to format URNs as a link

Render URNs on forwards in Sent messages folder

---

templates/cases/inbox_messages.haml
templates/cases/partner_read.haml

Sometimes.people.send.messages.like.this.perhaps.because.their.phone.doesnt.have.a.space.key.and.then.we.have.wrapping.problems.

Fix wrapping of message text when it doesn't contain spaces

---

casepro/cases/tests.py
casepro/settings_common.py
pip-freeze.txt

Most of the Django 1.9 required changes went into https://github.com/rapidpro/casepro/pull/160 so this just switches to the new custom HAML template loaders in Dash, and fixes a couple of redirect related unit tests.

Django 1.9

---

casepro/orgs_ext/forms.py

So that orgs can be created before users - you can create the admin users from the org dashboard

Make administrators field not required on org form 

---

casepro/backend/__init__.py

So that a dev instance can fire up the celery tasks without their own backend implementation

Ensure NoopBackend methods return suitable values

---

casepro/settings_common.py

django-redis 3.8 introduced support for redis-py style URLs - seems old format is silently ignored

Fix Redis location URL format

---

karma/test-controllers.coffee
karma/test-modals.coffee
static/coffee/controllers.coffee
static/coffee/modals.coffee

Changes new case and re-assign modals so they are responsible for fetching users. Right now the calling code fetches users initially, and the modal refreshes them if the partner selection changes - simpler to always have the modal do the fetching.

More user assignment tweaks

---

casepro/celery.py
casepro/settings_common.py
pip-freeze.txt
pip-requires.txt

And no so well maintained - doesn't have a Python 3 or Django 1.10 compatible release yet.
Need to ensure workers aren't being launched using the management command provided by django-celery, i.e. https://github.com/nyaruka/upartners/pull/2

Remove django-celery as it's not needed

---

casepro/contacts/models.py
casepro/contacts/tests.py
casepro/utils/__init__.py
casepro/utils/tests.py
karma/test-controllers.coffee
static/coffee/controllers.coffee
static/coffee/services.coffee
static/templates/modals/create_case.html

* Moves URN functionality into URN class
* Add support for normalizing URNs
* Fixes open case modal so required error not shown on Summary field unless form has been submitted
@KaitCrawford currently on the 'Open Case' modal, the user has to type a phone number in exactly E164 format, and sees an error message as they type. This PR doesn't address that but does add normalization on the server side, so it might be possible to relax that restriction and let users type things like "260 96-123-1234"

Contact URN tweaks

---

casepro/contacts/models.py
casepro/contacts/tests.py
casepro/settings_common.py

* Rename `Contact.get_display_name` to `Contact.get_display` for clarity
* Remove support for `SITE_ANON_CONTACTS` which has been replaced by `SITE_HIDE_CONTACT_FIELDS`
* Use placeholder (---) when there's nothing to display for a contact

Tweaks to contact displaying

---

templates/cases/inbox_base.haml

Ensure inbox header buttons are displayed as group

---

casepro/settings_common.py

We're getting a lot of these in Sentry but there's not much to be done about them, and this is how the Django docs recommend disabling the exceptions.

Disable exception reporting for DisallowedHost

---

.gitignore
casepro/profiles/context_processors.py
static/coffee/modals.coffee
static/less/cases.less
templates/cases/partner_read.haml
templates/msgs/faq_list.haml
templates/msgs/faq_read.haml
templates/partials/modal_reply.haml

* Makes styling more consistent with rest of app
* Fixes bug where reply modal isn't affected by whether user must use FAQs #199 
* Improves instructions on reply modal based on what user can do
Before:
After:
Before:
After:
Before:
After (when user isn't limited to FAQs and there are some):
After (when user isn't limited to FAQs and there aren't any):
After (when user is limited to FAQs and there are some):
After (when user is limited to FAQs and there aren't any):

FAQ fixes and UI tweaks

---

casepro/cases/views.py
templates/cases/inbox_messages.haml

Urns displayed on the inbox page are displaying poorly due to a lack of space.
This adjusts the css based on the SITE_CONTACT_DISPLAY setting
Before changes:
After changes:

Fix urn contact display

---

casepro/rules/models.py
casepro/rules/tests.py

👷 Actions should still succeed even if their backend operations fail

---

casepro/cases/management/commands/test_db.py
casepro/msgs/views.py
casepro/rules/templatetags/rules.py
casepro/rules/tests.py
templates/msgs/label_read.haml

Now that we allow labelling rules without keywords, important that users can see what rules they have created.

Render label rule tests on read page

---

casepro/cases/models.py
casepro/cases/tests.py

Instead of the entire partner org

If case is assigned to specific user, only notify that user

---

poetry.lock
pyproject.toml

Celery 4.4.7 attempts to use amqp despite being given Redis broker url
resolves rapidpro/casepro#348

Lock celery to v4.4.6

---

casepro/statistics/migrations/0015_populate_is_squashed.py

Get name of django model using `Model._meta.object_name` instead of
`Model.name`. Using `Model.name` raises an `AttributeError`

Fix 0015_populate_is_squashed migration in statistics app

---

casepro/backend/__init__.py
casepro/backend/rapidpro.py
casepro/backend/tests/test_rapidpro.py
casepro/cases/views.py
casepro/contacts/models.py
casepro/contacts/tests.py
casepro/contacts/views.py
casepro/settings_common.py
static/coffee/utils.coffee
templates/cases/case_read.haml
templates/contacts/contact_read.haml

The `push_contact` functionality was necessary for the Open Case button functionality. For this to work a few things are necessary, as summarised below:
- URNs need to be synced to CasePro to check if the URN already exists in both CasePro and RapidPro.
- URNs also needed to be hidden from the UI for privacy. I removed the `urn.path` from the frontend but left the placeholder.
- `push_contact` checks for the contact in RapidPro by the URN, if it doesn't exist, the contact is created in RapidPro and the RapidPro `uuid` is returned.
- `get_or_create_from_urn` looks for the contact in CasePro by the URN, if it does not exist, it gets the contact from RapidPro and its `uuid`, it then looks for the CasePro contact by the `uuid` to avoid duplicated, if it still doesn't exist, a new CasePro …

Add push contacts for rapidpro
