rapidpro/casepro

casepro/settings.py.prod
=> Change our API host to app.rapidpro.io

casepro/backend/__init__.py, casepro/backend/rapidpro.py, casepro/backend/tests/test_rapidpro.py, casepro/cases/models.py, casepro/cases/tests.py, casepro/contacts/models.py, casepro/msgs/migrations/0036_outgoing_partner.py, casepro/msgs/migrations/0037_outgoing_indexes.py, casepro/msgs/models.py, casepro/msgs/tests.py
* Added partner field to outgoing model which we'll need for any partner based view of sent messages
* Reworked case timeline so it doesn't rely on fetching messages from backend
=> Further outgoing message improvements

casepro/cases/urls.py, casepro/cases/views.py, casepro/msgs/models.py, casepro/msgs/tests.py, casepro/msgs/urls.py, casepro/msgs/views.py, casepro/settings_common.py, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/cases/home_base.haml, templates/cases/home_cases.haml, templates/cases/home_outgoing.haml
There's definitely more could be added here such as a modal dialog to list out recipients (up to 1000 URNs and contacts), but this at least for now that lets admins see who is sending what and track down messages they see appearing in RapidPro.
=> Basic sent folder

casepro/backend/__init__.py, casepro/settings_common.py, casepro/test.py
Makes it that little bit easier to get a development instance up and running
=> Make the default backend a NOOP backend

templates/profiles/user_read.haml
Adds "Become" button to user page for root users
=> Let root users easily become other users for testing

casepro/msgs/models.py
Seems to improve searching by 1.5-2x. Still need further improvement.
=> Use prefetch for contact in message search to avoid expensive join

casepro/cases/tests.py, casepro/cases/views.py, casepro/msgs/models.py, casepro/msgs/tests.py, casepro/test.py, karma/test-controllers.coffee, karma/test-services.coffee, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/cases/partner_read.haml
Instead of embedding it in the partner read page.
=> Fetch data for replies chart by AJAX

casepro/cases/models.py, casepro/cases/views.py, karma/test-controllers.coffee, static/coffee/controllers.coffee, templates/cases/case_read.haml
Now that there's an XHR way to grab a contact - updates the case read view to use it
=> Update case read view to use contact fetch endpoint 

static/coffee/modals.coffee, templates/cases/home_messages.haml, templates/partials/modal_compose.haml
Also fixes the inbox view so when clicking a message to expand it and get to the forward button - you don't have to click the actual message text but anywhere in that list item.
=> Email forwards

casepro/cases/migrations/0038_case_watchers.py, casepro/cases/models.py, casepro/cases/tests.py, casepro/cases/views.py, casepro/msgs/tasks.py, casepro/msgs/tests.py, casepro/orgs_ext/__init__.py, casepro/profiles/__init__.py, casepro/profiles/tests.py, casepro/settings_common.py, casepro/test.py, casepro/utils/email.py, casepro/utils/export.py, casepro/utils/tests.py, karma/test-controllers.coffee, karma/test-services.coffee, pip-freeze.txt, pip-requires.txt, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/cases/case_read.haml, templates/cases/email/case_notification.html, templates/cases/email/case_notification.txt
* Users automatically watch a case when engaging with it
* Can manually watch/unwatch from case page
* Email notifications sent to all watchers when certain case events occur, e.g. new reply, new note
=> Email notifications for case activity

casepro/cases/models.py, casepro/cases/tests.py, casepro/profiles/__init__.py, casepro/profiles/tests.py, casepro/profiles/views.py, casepro/statistics/models.py, casepro/statistics/signals.py, static/coffee/controllers.coffee, templates/profiles/user_read.haml
Reworks existing user read page into a simple dashboard in the same style as that for labels, partners etc.
=> User dashboard

templates/profiles/user_read.haml
Change "Become User" button to use a regular post submission rather than ajax request. Now works on staging server.
=> Fix "Become" button on user read page not always redirecting

casepro/statistics/tests.py, casepro/statistics/urls.py, casepro/statistics/views.py, karma/test-controllers.coffee, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/frame.haml, templates/orgs_ext/org_home.haml
* Line chart of number of incoming messages per day
* Pie chart of most commonly applied labels in last 30 days
=> New org dashboard summary charts

casepro/contacts/tests.py, casepro/contacts/views.py, karma/test-controllers.coffee, karma/test-services.coffee, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/contacts/contact_read.haml
Note that the cases displayed are only the ones that the current user has access to.
=> List a contact's cases on their read page

templates/smartmin/users/login.haml
=> Improve appearance of login page

casepro/cases/tests.py, casepro/pods/tests/utils.py, templates/cases/case_read.haml
Offline compression is currently broken so this just disables compression for pod resources. We can put it back in future, just need compression working again for now.
=> Don't use django-compressor with pod resources

casepro/cases/forms.py, casepro/cases/tests.py, casepro/cases/views.py, casepro/msgs/tests.py, casepro/msgs/views.py, casepro/profiles/tests.py, casepro/profiles/views.py, static/coffee/controllers.coffee
* Fixes "Select All" on inbox page which currently leads to Javascript error.
* Fixes label create form from redirecting to a JSON endpoint, and changes it and the partner and user create forms to all redirect to their model's read page.
* Tweaks partner form to use textarea for description like on label form.
=> Bugs and tweaks

casepro/cases/management/commands/bootstrap_dev.py, static/coffee/controllers.coffee, templates/cases/inbox_messages.haml, templates/partials/modal_reply.haml
The idea here was to improve end-user usability by adding a Reply button to the inline message actions between Open Case and Forward.
=> Add inline reply to message button

casepro/msg_board/__init__.py, casepro/msg_board/migrations/0001_initial.py, casepro/msg_board/models.py, casepro/msg_board/tests.py, casepro/msg_board/urls.py, casepro/msg_board/views.py, casepro/settings_common.py, casepro/urls.py, karma/test-controllers.coffee, pip-freeze.txt, pip-requires.txt, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/comments/form.html, templates/frame.haml, templates/msg_board/comment_list.haml
=> Implement message board in case pro

karma/test-controllers.coffee, static/coffee/controllers.coffee, templates/cases/partner_read.haml
Also fixes permissions so superusers can delete partners.
Fixes https://github.com/rapidpro/casepro/issues/146
=> Fix redirects on label/partner deletion. 

karma/test-controllers.coffee, static/coffee/controllers.coffee
Fixes https://github.com/rapidpro/casepro/issues/151
=> Fix for filtering cases by assignee

casepro/statistics/migrations/0008_existing_case_stats_count.py, templates/orgs_ext/org_home.haml
- Adds progress output to migration
- Fixes header case on partner tab of org dashboard
=> Case count tweaks

casepro/cases/tests.py, karma/test-modals.coffee, static/coffee/modals.coffee, templates/cases/case_read.haml, templates/partials/modal_assign.haml
=> User assignment tweaks

pip-freeze.txt
=> Update to django-compressor 2.1

casepro/orgs_ext/tests.py, casepro/statistics/models.py, casepro/test.py, pip-freeze.txt
Which makes `Org.timezone` an actual timezone
=> Update to latest dash

casepro/cases/tests.py, templates/frame.haml
=> Fix partner users not being able to access the message board

static/css/pods.css
Fixed word wrapping issue on Pods, and cleaned up styling 
**Before:**
**After:**
=> Feature/pods word wrap + styling

casepro/profiles/tests.py, casepro/profiles/views.py
=> Incorrect value shown for total cases in stags

casepro/backend/junebug.py, casepro/backend/tests/test_junebug.py
We need to pass the Outgoing message creator to Junebug Hub
=> send created_by__id to junebug hub

casepro/msgs/forms.py, casepro/msgs/views.py
The labels should be a empty list instead of None.
=> Issue 196 cant edit faq translations.

casepro/msgs/models.py, casepro/msgs/tests.py
Added parent labels if FAQ is a translations.
=> Issue 197 faq translations dont appear with labels on the reply modal

pip-freeze.txt, templates/cases/case_read.haml, templates/cases/inbox_cases.haml, templates/cases/inbox_messages.haml, templates/cases/inbox_outgoing.haml, templates/cases/partner_read.haml, templates/contacts/contact_read.haml, templates/frame.haml, templates/msg_board/comment_list.haml, templates/msgs/label_read.haml, templates/orgs_ext/org_home.haml, templates/partials/modal_messagehistory.haml, templates/partials/popover_contact.haml, templates/profiles/user_read.haml
I've finally fixed the bug in https://github.com/nyaruka/django-hamlpy that was preventing it supporting tags with hypens
=> Update to latest django-hamlpy

casepro/settings_common.py, pip-freeze.txt
Saves filling celery up with these
=> Don't have celery store task results as these are modelled internally

casepro/cases/views.py, casepro/msgs/context_processors.py, casepro/profiles/context_processors.py, casepro/settings_common.py
- Add context processor to msgs app and set max_msg_chars there instead of in profiles app
- Change default to 160
=> Tweaks to how max_msg_chars is set

casepro/backend/junebug.py, casepro/backend/tests/test_junebug.py
We currently have an issue where every message coming into Casepro is getting a collision. Not sure how this is possible, must be something to do with the lower bits of a uuid4. Either way, this PR adds some additional robustness, by attempting to generate a random ID if there is a collision with the lower bits of the UUID.
=> Add collision prevention for Junebug inbound message keys

casepro/backend/junebug.py, casepro/backend/tests/test_junebug.py
Currently, we have an issue that if the phone number from the service provider is not normalised, it creates duplicate identities in our identity store. We should normalise these phone numbers in the search for identities, and when creating a new identity, to ensure that all phone numbers in the identity store are normalised.
=> Add phone number normalization for inbound messages on Junebug backend

casepro/msgs/models.py
Start using modified_on to fetch messages that have been acted on or locked
=> Refresh fix pt3

casepro/contacts/models.py, casepro/msgs/forms.py, casepro/msgs/models.py, casepro/msgs/tests.py
Fixes https://github.com/rapidpro/casepro/issues/221
=> Don't allow label names which are invalid in RapidPro

casepro/cases/views.py, casepro/msgs/models.py, casepro/msgs/tests.py, casepro/msgs/views.py, karma/test-controllers.coffee, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/cases/inbox_messages.haml
This should be done by labelling by group and then we can optimize per-label access
=> Remove search by group

templates/partials/modal_faq.haml
This PR fixes language selection on creating/editing a FAQ.
=> Fix FAQ language selection

.gitignore, casepro/backend/__init__.py, casepro/backend/junebug.py, casepro/backend/rapidpro.py, casepro/backend/tests/test_rapidpro.py, casepro/cases/models.py, casepro/contacts/management/commands/pullcontacts.py, casepro/contacts/models.py, casepro/contacts/tasks.py, casepro/msgs/management/commands/pullmessages.py, casepro/msgs/models.py, casepro/msgs/signals.py, casepro/msgs/tasks.py, casepro/orgs_ext/views.py, casepro/rules/models.py, casepro/settings_common.py, casepro/test.py, casepro/urls.py, pip-freeze.txt, templates/orgs_ext/org_home.haml
-Migrations for org config
-Use OrgBackend object
=> Update rapidpro-dash 

casepro/backend/__init__.py, casepro/backend/junebug.py, casepro/backend/rapidpro.py, casepro/backend/tests/test_rapidpro.py, casepro/cases/models.py, casepro/cases/tests.py, casepro/orgs_ext/forms.py, casepro/orgs_ext/models.py, casepro/orgs_ext/tests.py, casepro/orgs_ext/views.py
=> Follow-up flows when a case is closed

casepro/cases/management/commands/test_db.py
Need to create a big database of messages with labels for testing
=> 🔧 Add management command to create test database

casepro/msgs/models.py, casepro/msgs/tests.py, casepro/msgs/views.py
Rework message searching to use new fields on labelling
=> Faster searching part 4

casepro/msgs/tests.py, casepro/rules/mixins.py
=> Allow rules without keywords

casepro/orgs_ext/views.py, casepro/rules/templatetags/rules.py, casepro/rules/tests.py, casepro/rules/views.py, templates/orgs_ext/org_home.haml, templates/rules/rule_list.haml
This has always been around but finally tidying it up and making it accessible to users and not just me..
=> Rules list

casepro/cases/views.py, casepro/msgs/models.py, casepro/msgs/tests.py, static/coffee/controllers.coffee, templates/cases/inbox_base.haml, templates/cases/inbox_messages.haml
=> 🔎 Limit searching by text to the last 90 days

casepro/msgs/models.py, casepro/msgs/tests.py
Fixes blow up caused by method getting the same keyword argument twice
=> Fix searching by text and date

casepro/cases/models.py, casepro/cases/tests.py, casepro/cases/views.py, casepro/test.py, static/coffee/controllers.coffee, static/coffee/services.coffee, templates/profiles/user_read.haml
=> Add tab to user page which lists cases assigned to them

casepro/profiles/tests.py, casepro/profiles/views.py
Fixes https://github.com/rapidpro/casepro/issues/279
=> Fix editing of must_use_faq

casepro/cases/forms.py, casepro/msgs/models.py, templates/cases/partner_create.haml, templates/cases/partner_update.haml
Fix styling on partner update/create forms and add validator for image file extensions
=> Partner form fixes

casepro/cases/views.py, casepro/contacts/views.py, casepro/msgs/views.py, casepro/profiles/views.py, templates/cases/case_read.haml, templates/cases/inbox_base.haml, templates/cases/partner_read.haml, templates/contacts/contact_read.haml, templates/msgs/faq_read.haml, templates/msgs/label_read.haml, templates/profiles/user_read.haml
Use Django json_script filter when embedding JSON in a template
=> Fix XSS vulnerability

casepro/backend/rapidpro.py, casepro/backend/tests/test_rapidpro.py
Fixes https://github.com/rapidpro/casepro/issues/325
=> Fix wrong arg name for latest rapidpro client

casepro/rules/templatetags/rules.py, casepro/rules/tests.py
And checked this is the only place where we use `mark_safe`
=> 👮 Fix XSS vulnerabilities in rules template tags

templates/cases/inbox_cases.haml
=> Add case id to case list views
